### PR TITLE
Add a Remnant Hint mission

### PR DESCRIPTION
**Pull request by TheGiraffe3**
As the title says, get a mission up and running. I only have one, and it’s a poor draft, but it’s a starting point. 
Also, this will update the branch to the latest master.

### CODE REVIEW

**Comment by TheGiraffe3** [comment]
@Zarkonnen status?

**Comment by TheGiraffe3** [comment]
@Zarkonnen status?

**Comment by Zarkonnen** [comment]
> @Zarkonnen status?

Currently bashing my head against C++ for conditional shop contents. :D

**Comment by TheGiraffe3** [comment]
@Zarkonnen if you ever need anything more to work on (which seems unlikely), you could work on [this](https://github.com/endless-sky/endless-sky/issues/5800).

**Pull request merged**
